create extension if not exists pgcrypto;

create table if not exists public.showcase_works (
  id text primary key,
  name text not null,
  display_order int not null unique
);

insert into public.showcase_works (id, name, display_order) values
  ('yy', '原毓', 1),
  ('dc', '道翀', 2),
  ('lt', '林通', 3),
  ('yufan', '羽帆', 4),
  ('ym', '堉铭', 5),
  ('ziyi', '梓依', 6),
  ('hs', '泓胜', 7),
  ('jh', '靖淮', 8)
on conflict (id) do update
set name = excluded.name,
    display_order = excluded.display_order;

create table if not exists public.showcase_votes (
  id bigint generated by default as identity primary key,
  work_id text not null references public.showcase_works(id) on delete cascade,
  voter_id uuid not null,
  created_at timestamptz not null default now(),
  constraint showcase_votes_unique unique (work_id, voter_id)
);

create index if not exists showcase_votes_voter_id_idx on public.showcase_votes (voter_id);
create index if not exists showcase_votes_work_id_idx on public.showcase_votes (work_id);

alter table public.showcase_works enable row level security;
alter table public.showcase_votes enable row level security;

create or replace function public.get_showcase_vote_totals()
returns table (work_id text, total_votes bigint)
language sql
security definer
set search_path = public
as $$
  select w.id as work_id, count(v.id)::bigint as total_votes
  from public.showcase_works w
  left join public.showcase_votes v on v.work_id = w.id
  group by w.id
  order by w.id;
$$;

create or replace function public.get_showcase_voter_votes(p_voter_id uuid)
returns table (work_id text)
language sql
security definer
set search_path = public
as $$
  select v.work_id
  from public.showcase_votes v
  where v.voter_id = p_voter_id
  order by v.created_at asc;
$$;

create or replace function public.cast_showcase_vote(p_voter_id uuid, p_work_id text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  vote_count integer;
begin
  if not exists (select 1 from public.showcase_works where id = p_work_id) then
    return jsonb_build_object('ok', false, 'reason', 'invalid_work');
  end if;

  if exists (
    select 1
    from public.showcase_votes
    where voter_id = p_voter_id
      and work_id = p_work_id
  ) then
    return jsonb_build_object('ok', false, 'reason', 'already_voted');
  end if;

  select count(*) into vote_count
  from public.showcase_votes
  where voter_id = p_voter_id;

  if vote_count >= 3 then
    return jsonb_build_object('ok', false, 'reason', 'limit_reached');
  end if;

  insert into public.showcase_votes (work_id, voter_id)
  values (p_work_id, p_voter_id);

  return jsonb_build_object('ok', true);
end;
$$;

grant execute on function public.get_showcase_vote_totals() to anon, authenticated;
grant execute on function public.get_showcase_voter_votes(uuid) to anon, authenticated;
grant execute on function public.cast_showcase_vote(uuid, text) to anon, authenticated;
